// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ClientRPCService is an autogenerated mock type for the ClientRPCService type
type ClientRPCService struct {
	mock.Mock
}

type ClientRPCService_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientRPCService) EXPECT() *ClientRPCService_Expecter {
	return &ClientRPCService_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, serviceMethod, args, reply
func (_m *ClientRPCService) Call(ctx context.Context, serviceMethod string, args interface{}, reply interface{}) error {
	ret := _m.Called(ctx, serviceMethod, args, reply)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, interface{}) error); ok {
		r0 = rf(ctx, serviceMethod, args, reply)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRPCService_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type ClientRPCService_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//  - ctx context.Context
//  - serviceMethod string
//  - args interface{}
//  - reply interface{}
func (_e *ClientRPCService_Expecter) Call(ctx interface{}, serviceMethod interface{}, args interface{}, reply interface{}) *ClientRPCService_Call_Call {
	return &ClientRPCService_Call_Call{Call: _e.mock.On("Call", ctx, serviceMethod, args, reply)}
}

func (_c *ClientRPCService_Call_Call) Run(run func(ctx context.Context, serviceMethod string, args interface{}, reply interface{})) *ClientRPCService_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(interface{}))
	})
	return _c
}

func (_c *ClientRPCService_Call_Call) Return(_a0 error) *ClientRPCService_Call_Call {
	_c.Call.Return(_a0)
	return _c
}

// CheckOnline provides a mock function with given fields:
func (_m *ClientRPCService) CheckOnline() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ClientRPCService_CheckOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOnline'
type ClientRPCService_CheckOnline_Call struct {
	*mock.Call
}

// CheckOnline is a helper method to define mock.On call
func (_e *ClientRPCService_Expecter) CheckOnline() *ClientRPCService_CheckOnline_Call {
	return &ClientRPCService_CheckOnline_Call{Call: _e.mock.On("CheckOnline")}
}

func (_c *ClientRPCService_CheckOnline_Call) Run(run func()) *ClientRPCService_CheckOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientRPCService_CheckOnline_Call) Return(_a0 bool) *ClientRPCService_CheckOnline_Call {
	_c.Call.Return(_a0)
	return _c
}

// LoadRecordBankCardByKey provides a mock function with given fields: ctx, token, key
func (_m *ClientRPCService) LoadRecordBankCardByKey(ctx context.Context, token string, key string) (string, error) {
	ret := _m.Called(ctx, token, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, token, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRPCService_LoadRecordBankCardByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRecordBankCardByKey'
type ClientRPCService_LoadRecordBankCardByKey_Call struct {
	*mock.Call
}

// LoadRecordBankCardByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
func (_e *ClientRPCService_Expecter) LoadRecordBankCardByKey(ctx interface{}, token interface{}, key interface{}) *ClientRPCService_LoadRecordBankCardByKey_Call {
	return &ClientRPCService_LoadRecordBankCardByKey_Call{Call: _e.mock.On("LoadRecordBankCardByKey", ctx, token, key)}
}

func (_c *ClientRPCService_LoadRecordBankCardByKey_Call) Run(run func(ctx context.Context, token string, key string)) *ClientRPCService_LoadRecordBankCardByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_LoadRecordBankCardByKey_Call) Return(_a0 string, _a1 error) *ClientRPCService_LoadRecordBankCardByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// LoadRecordBinaryDataByKey provides a mock function with given fields: ctx, token, key
func (_m *ClientRPCService) LoadRecordBinaryDataByKey(ctx context.Context, token string, key string) (string, error) {
	ret := _m.Called(ctx, token, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, token, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRPCService_LoadRecordBinaryDataByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRecordBinaryDataByKey'
type ClientRPCService_LoadRecordBinaryDataByKey_Call struct {
	*mock.Call
}

// LoadRecordBinaryDataByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
func (_e *ClientRPCService_Expecter) LoadRecordBinaryDataByKey(ctx interface{}, token interface{}, key interface{}) *ClientRPCService_LoadRecordBinaryDataByKey_Call {
	return &ClientRPCService_LoadRecordBinaryDataByKey_Call{Call: _e.mock.On("LoadRecordBinaryDataByKey", ctx, token, key)}
}

func (_c *ClientRPCService_LoadRecordBinaryDataByKey_Call) Run(run func(ctx context.Context, token string, key string)) *ClientRPCService_LoadRecordBinaryDataByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_LoadRecordBinaryDataByKey_Call) Return(_a0 string, _a1 error) *ClientRPCService_LoadRecordBinaryDataByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// LoadRecordPersonalDataByKey provides a mock function with given fields: ctx, token, key
func (_m *ClientRPCService) LoadRecordPersonalDataByKey(ctx context.Context, token string, key string) (string, error) {
	ret := _m.Called(ctx, token, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, token, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRPCService_LoadRecordPersonalDataByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRecordPersonalDataByKey'
type ClientRPCService_LoadRecordPersonalDataByKey_Call struct {
	*mock.Call
}

// LoadRecordPersonalDataByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
func (_e *ClientRPCService_Expecter) LoadRecordPersonalDataByKey(ctx interface{}, token interface{}, key interface{}) *ClientRPCService_LoadRecordPersonalDataByKey_Call {
	return &ClientRPCService_LoadRecordPersonalDataByKey_Call{Call: _e.mock.On("LoadRecordPersonalDataByKey", ctx, token, key)}
}

func (_c *ClientRPCService_LoadRecordPersonalDataByKey_Call) Run(run func(ctx context.Context, token string, key string)) *ClientRPCService_LoadRecordPersonalDataByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_LoadRecordPersonalDataByKey_Call) Return(_a0 string, _a1 error) *ClientRPCService_LoadRecordPersonalDataByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// LoadRecordTextDataByKey provides a mock function with given fields: ctx, token, key
func (_m *ClientRPCService) LoadRecordTextDataByKey(ctx context.Context, token string, key string) (string, error) {
	ret := _m.Called(ctx, token, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, token, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRPCService_LoadRecordTextDataByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRecordTextDataByKey'
type ClientRPCService_LoadRecordTextDataByKey_Call struct {
	*mock.Call
}

// LoadRecordTextDataByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
func (_e *ClientRPCService_Expecter) LoadRecordTextDataByKey(ctx interface{}, token interface{}, key interface{}) *ClientRPCService_LoadRecordTextDataByKey_Call {
	return &ClientRPCService_LoadRecordTextDataByKey_Call{Call: _e.mock.On("LoadRecordTextDataByKey", ctx, token, key)}
}

func (_c *ClientRPCService_LoadRecordTextDataByKey_Call) Run(run func(ctx context.Context, token string, key string)) *ClientRPCService_LoadRecordTextDataByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_LoadRecordTextDataByKey_Call) Return(_a0 string, _a1 error) *ClientRPCService_LoadRecordTextDataByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *ClientRPCService) Login(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRPCService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type ClientRPCService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//  - ctx context.Context
//  - username string
//  - password string
func (_e *ClientRPCService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *ClientRPCService_Login_Call {
	return &ClientRPCService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *ClientRPCService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *ClientRPCService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_Login_Call) Return(_a0 string, _a1 error) *ClientRPCService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Register provides a mock function with given fields: ctx, username, password
func (_m *ClientRPCService) Register(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRPCService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type ClientRPCService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//  - ctx context.Context
//  - username string
//  - password string
func (_e *ClientRPCService_Expecter) Register(ctx interface{}, username interface{}, password interface{}) *ClientRPCService_Register_Call {
	return &ClientRPCService_Register_Call{Call: _e.mock.On("Register", ctx, username, password)}
}

func (_c *ClientRPCService_Register_Call) Run(run func(ctx context.Context, username string, password string)) *ClientRPCService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_Register_Call) Return(_a0 string, _a1 error) *ClientRPCService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RemoveRecordBankCardByKey provides a mock function with given fields: ctx, token, key
func (_m *ClientRPCService) RemoveRecordBankCardByKey(ctx context.Context, token string, key string) error {
	ret := _m.Called(ctx, token, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRPCService_RemoveRecordBankCardByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRecordBankCardByKey'
type ClientRPCService_RemoveRecordBankCardByKey_Call struct {
	*mock.Call
}

// RemoveRecordBankCardByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
func (_e *ClientRPCService_Expecter) RemoveRecordBankCardByKey(ctx interface{}, token interface{}, key interface{}) *ClientRPCService_RemoveRecordBankCardByKey_Call {
	return &ClientRPCService_RemoveRecordBankCardByKey_Call{Call: _e.mock.On("RemoveRecordBankCardByKey", ctx, token, key)}
}

func (_c *ClientRPCService_RemoveRecordBankCardByKey_Call) Run(run func(ctx context.Context, token string, key string)) *ClientRPCService_RemoveRecordBankCardByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_RemoveRecordBankCardByKey_Call) Return(_a0 error) *ClientRPCService_RemoveRecordBankCardByKey_Call {
	_c.Call.Return(_a0)
	return _c
}

// RemoveRecordBinaryDataByKey provides a mock function with given fields: ctx, token, key
func (_m *ClientRPCService) RemoveRecordBinaryDataByKey(ctx context.Context, token string, key string) error {
	ret := _m.Called(ctx, token, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRPCService_RemoveRecordBinaryDataByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRecordBinaryDataByKey'
type ClientRPCService_RemoveRecordBinaryDataByKey_Call struct {
	*mock.Call
}

// RemoveRecordBinaryDataByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
func (_e *ClientRPCService_Expecter) RemoveRecordBinaryDataByKey(ctx interface{}, token interface{}, key interface{}) *ClientRPCService_RemoveRecordBinaryDataByKey_Call {
	return &ClientRPCService_RemoveRecordBinaryDataByKey_Call{Call: _e.mock.On("RemoveRecordBinaryDataByKey", ctx, token, key)}
}

func (_c *ClientRPCService_RemoveRecordBinaryDataByKey_Call) Run(run func(ctx context.Context, token string, key string)) *ClientRPCService_RemoveRecordBinaryDataByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_RemoveRecordBinaryDataByKey_Call) Return(_a0 error) *ClientRPCService_RemoveRecordBinaryDataByKey_Call {
	_c.Call.Return(_a0)
	return _c
}

// RemoveRecordPersonalDataByKey provides a mock function with given fields: ctx, token, key
func (_m *ClientRPCService) RemoveRecordPersonalDataByKey(ctx context.Context, token string, key string) error {
	ret := _m.Called(ctx, token, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRPCService_RemoveRecordPersonalDataByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRecordPersonalDataByKey'
type ClientRPCService_RemoveRecordPersonalDataByKey_Call struct {
	*mock.Call
}

// RemoveRecordPersonalDataByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
func (_e *ClientRPCService_Expecter) RemoveRecordPersonalDataByKey(ctx interface{}, token interface{}, key interface{}) *ClientRPCService_RemoveRecordPersonalDataByKey_Call {
	return &ClientRPCService_RemoveRecordPersonalDataByKey_Call{Call: _e.mock.On("RemoveRecordPersonalDataByKey", ctx, token, key)}
}

func (_c *ClientRPCService_RemoveRecordPersonalDataByKey_Call) Run(run func(ctx context.Context, token string, key string)) *ClientRPCService_RemoveRecordPersonalDataByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_RemoveRecordPersonalDataByKey_Call) Return(_a0 error) *ClientRPCService_RemoveRecordPersonalDataByKey_Call {
	_c.Call.Return(_a0)
	return _c
}

// RemoveRecordTextDataByKey provides a mock function with given fields: ctx, token, key
func (_m *ClientRPCService) RemoveRecordTextDataByKey(ctx context.Context, token string, key string) error {
	ret := _m.Called(ctx, token, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRPCService_RemoveRecordTextDataByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRecordTextDataByKey'
type ClientRPCService_RemoveRecordTextDataByKey_Call struct {
	*mock.Call
}

// RemoveRecordTextDataByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
func (_e *ClientRPCService_Expecter) RemoveRecordTextDataByKey(ctx interface{}, token interface{}, key interface{}) *ClientRPCService_RemoveRecordTextDataByKey_Call {
	return &ClientRPCService_RemoveRecordTextDataByKey_Call{Call: _e.mock.On("RemoveRecordTextDataByKey", ctx, token, key)}
}

func (_c *ClientRPCService_RemoveRecordTextDataByKey_Call) Run(run func(ctx context.Context, token string, key string)) *ClientRPCService_RemoveRecordTextDataByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClientRPCService_RemoveRecordTextDataByKey_Call) Return(_a0 error) *ClientRPCService_RemoveRecordTextDataByKey_Call {
	_c.Call.Return(_a0)
	return _c
}

// SaveRecordBankCard provides a mock function with given fields: ctx, token, key, data
func (_m *ClientRPCService) SaveRecordBankCard(ctx context.Context, token string, key string, data string) error {
	ret := _m.Called(ctx, token, key, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, token, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRPCService_SaveRecordBankCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRecordBankCard'
type ClientRPCService_SaveRecordBankCard_Call struct {
	*mock.Call
}

// SaveRecordBankCard is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
//  - data string
func (_e *ClientRPCService_Expecter) SaveRecordBankCard(ctx interface{}, token interface{}, key interface{}, data interface{}) *ClientRPCService_SaveRecordBankCard_Call {
	return &ClientRPCService_SaveRecordBankCard_Call{Call: _e.mock.On("SaveRecordBankCard", ctx, token, key, data)}
}

func (_c *ClientRPCService_SaveRecordBankCard_Call) Run(run func(ctx context.Context, token string, key string, data string)) *ClientRPCService_SaveRecordBankCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ClientRPCService_SaveRecordBankCard_Call) Return(_a0 error) *ClientRPCService_SaveRecordBankCard_Call {
	_c.Call.Return(_a0)
	return _c
}

// SaveRecordBinaryData provides a mock function with given fields: ctx, token, key, data
func (_m *ClientRPCService) SaveRecordBinaryData(ctx context.Context, token string, key string, data string) error {
	ret := _m.Called(ctx, token, key, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, token, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRPCService_SaveRecordBinaryData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRecordBinaryData'
type ClientRPCService_SaveRecordBinaryData_Call struct {
	*mock.Call
}

// SaveRecordBinaryData is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
//  - data string
func (_e *ClientRPCService_Expecter) SaveRecordBinaryData(ctx interface{}, token interface{}, key interface{}, data interface{}) *ClientRPCService_SaveRecordBinaryData_Call {
	return &ClientRPCService_SaveRecordBinaryData_Call{Call: _e.mock.On("SaveRecordBinaryData", ctx, token, key, data)}
}

func (_c *ClientRPCService_SaveRecordBinaryData_Call) Run(run func(ctx context.Context, token string, key string, data string)) *ClientRPCService_SaveRecordBinaryData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ClientRPCService_SaveRecordBinaryData_Call) Return(_a0 error) *ClientRPCService_SaveRecordBinaryData_Call {
	_c.Call.Return(_a0)
	return _c
}

// SaveRecordPersonalData provides a mock function with given fields: ctx, token, key, data
func (_m *ClientRPCService) SaveRecordPersonalData(ctx context.Context, token string, key string, data string) error {
	ret := _m.Called(ctx, token, key, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, token, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRPCService_SaveRecordPersonalData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRecordPersonalData'
type ClientRPCService_SaveRecordPersonalData_Call struct {
	*mock.Call
}

// SaveRecordPersonalData is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
//  - data string
func (_e *ClientRPCService_Expecter) SaveRecordPersonalData(ctx interface{}, token interface{}, key interface{}, data interface{}) *ClientRPCService_SaveRecordPersonalData_Call {
	return &ClientRPCService_SaveRecordPersonalData_Call{Call: _e.mock.On("SaveRecordPersonalData", ctx, token, key, data)}
}

func (_c *ClientRPCService_SaveRecordPersonalData_Call) Run(run func(ctx context.Context, token string, key string, data string)) *ClientRPCService_SaveRecordPersonalData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ClientRPCService_SaveRecordPersonalData_Call) Return(_a0 error) *ClientRPCService_SaveRecordPersonalData_Call {
	_c.Call.Return(_a0)
	return _c
}

// SaveRecordTextData provides a mock function with given fields: ctx, token, key, data
func (_m *ClientRPCService) SaveRecordTextData(ctx context.Context, token string, key string, data string) error {
	ret := _m.Called(ctx, token, key, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, token, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientRPCService_SaveRecordTextData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRecordTextData'
type ClientRPCService_SaveRecordTextData_Call struct {
	*mock.Call
}

// SaveRecordTextData is a helper method to define mock.On call
//  - ctx context.Context
//  - token string
//  - key string
//  - data string
func (_e *ClientRPCService_Expecter) SaveRecordTextData(ctx interface{}, token interface{}, key interface{}, data interface{}) *ClientRPCService_SaveRecordTextData_Call {
	return &ClientRPCService_SaveRecordTextData_Call{Call: _e.mock.On("SaveRecordTextData", ctx, token, key, data)}
}

func (_c *ClientRPCService_SaveRecordTextData_Call) Run(run func(ctx context.Context, token string, key string, data string)) *ClientRPCService_SaveRecordTextData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ClientRPCService_SaveRecordTextData_Call) Return(_a0 error) *ClientRPCService_SaveRecordTextData_Call {
	_c.Call.Return(_a0)
	return _c
}

// NewClientRPCService creates a new instance of ClientRPCService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientRPCService(t testing.TB) *ClientRPCService {
	mock := &ClientRPCService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
