// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	context "context"
	clientmodels "gophkeeper/client/clientmodels"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ClientStorageService is an autogenerated mock type for the ClientStorageService type
type ClientStorageService struct {
	mock.Mock
}

// LoadRecords provides a mock function with given fields: ctx
func (_m *ClientStorageService) LoadRecords(ctx context.Context) ([]clientmodels.RecordFileLine, error) {
	ret := _m.Called(ctx)

	var r0 []clientmodels.RecordFileLine
	if rf, ok := ret.Get(0).(func(context.Context) []clientmodels.RecordFileLine); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]clientmodels.RecordFileLine)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncServer provides a mock function with given fields: ctx
func (_m *ClientStorageService) SyncServer(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClientStorageService creates a new instance of ClientStorageService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientStorageService(t testing.TB) *ClientStorageService {
	mock := &ClientStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
