// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	clientmodels "gophkeeper/client/clientmodels"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ActionFileStoreWriter is an autogenerated mock type for the ActionFileStoreWriter type
type ActionFileStoreWriter struct {
	mock.Mock
}

type ActionFileStoreWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *ActionFileStoreWriter) EXPECT() *ActionFileStoreWriter_Expecter {
	return &ActionFileStoreWriter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *ActionFileStoreWriter) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActionFileStoreWriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ActionFileStoreWriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ActionFileStoreWriter_Expecter) Close() *ActionFileStoreWriter_Close_Call {
	return &ActionFileStoreWriter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ActionFileStoreWriter_Close_Call) Run(run func()) *ActionFileStoreWriter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ActionFileStoreWriter_Close_Call) Return(_a0 error) *ActionFileStoreWriter_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

// SaveActions provides a mock function with given fields: actions
func (_m *ActionFileStoreWriter) SaveActions(actions clientmodels.StoreActions) error {
	ret := _m.Called(actions)

	var r0 error
	if rf, ok := ret.Get(0).(func(clientmodels.StoreActions) error); ok {
		r0 = rf(actions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActionFileStoreWriter_SaveActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveActions'
type ActionFileStoreWriter_SaveActions_Call struct {
	*mock.Call
}

// SaveActions is a helper method to define mock.On call
//  - actions clientmodels.StoreActions
func (_e *ActionFileStoreWriter_Expecter) SaveActions(actions interface{}) *ActionFileStoreWriter_SaveActions_Call {
	return &ActionFileStoreWriter_SaveActions_Call{Call: _e.mock.On("SaveActions", actions)}
}

func (_c *ActionFileStoreWriter_SaveActions_Call) Run(run func(actions clientmodels.StoreActions)) *ActionFileStoreWriter_SaveActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(clientmodels.StoreActions))
	})
	return _c
}

func (_c *ActionFileStoreWriter_SaveActions_Call) Return(_a0 error) *ActionFileStoreWriter_SaveActions_Call {
	_c.Call.Return(_a0)
	return _c
}

// NewActionFileStoreWriter creates a new instance of ActionFileStoreWriter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewActionFileStoreWriter(t testing.TB) *ActionFileStoreWriter {
	mock := &ActionFileStoreWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
