// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	context "context"
	clientmodels "gophkeeper/client/clientmodels"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// RecordBinaryDataService is an autogenerated mock type for the RecordBinaryDataService type
type RecordBinaryDataService struct {
	mock.Mock
}

// LoadRecordByKey provides a mock function with given fields: ctx, key
func (_m *RecordBinaryDataService) LoadRecordByKey(ctx context.Context, key string) (clientmodels.RecordBinaryData, error) {
	ret := _m.Called(ctx, key)

	var r0 clientmodels.RecordBinaryData
	if rf, ok := ret.Get(0).(func(context.Context, string) clientmodels.RecordBinaryData); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(clientmodels.RecordBinaryData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveRecordByKey provides a mock function with given fields: ctx, key
func (_m *RecordBinaryDataService) RemoveRecordByKey(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveRecord provides a mock function with given fields: ctx, key, data
func (_m *RecordBinaryDataService) SaveRecord(ctx context.Context, key string, data clientmodels.RecordBinaryData) error {
	ret := _m.Called(ctx, key, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, clientmodels.RecordBinaryData) error); ok {
		r0 = rf(ctx, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecordBinaryDataService creates a new instance of RecordBinaryDataService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewRecordBinaryDataService(t testing.TB) *RecordBinaryDataService {
	mock := &RecordBinaryDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
