// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	context "context"
	clientmodels "gophkeeper/client/clientmodels"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// RecordTextDataService is an autogenerated mock type for the RecordTextDataService type
type RecordTextDataService struct {
	mock.Mock
}

type RecordTextDataService_Expecter struct {
	mock *mock.Mock
}

func (_m *RecordTextDataService) EXPECT() *RecordTextDataService_Expecter {
	return &RecordTextDataService_Expecter{mock: &_m.Mock}
}

// LoadRecordByKey provides a mock function with given fields: ctx, key
func (_m *RecordTextDataService) LoadRecordByKey(ctx context.Context, key string) (clientmodels.RecordTextData, error) {
	ret := _m.Called(ctx, key)

	var r0 clientmodels.RecordTextData
	if rf, ok := ret.Get(0).(func(context.Context, string) clientmodels.RecordTextData); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(clientmodels.RecordTextData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordTextDataService_LoadRecordByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRecordByKey'
type RecordTextDataService_LoadRecordByKey_Call struct {
	*mock.Call
}

// LoadRecordByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - key string
func (_e *RecordTextDataService_Expecter) LoadRecordByKey(ctx interface{}, key interface{}) *RecordTextDataService_LoadRecordByKey_Call {
	return &RecordTextDataService_LoadRecordByKey_Call{Call: _e.mock.On("LoadRecordByKey", ctx, key)}
}

func (_c *RecordTextDataService_LoadRecordByKey_Call) Run(run func(ctx context.Context, key string)) *RecordTextDataService_LoadRecordByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RecordTextDataService_LoadRecordByKey_Call) Return(_a0 clientmodels.RecordTextData, _a1 error) *RecordTextDataService_LoadRecordByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RemoveRecordByKey provides a mock function with given fields: ctx, key
func (_m *RecordTextDataService) RemoveRecordByKey(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecordTextDataService_RemoveRecordByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRecordByKey'
type RecordTextDataService_RemoveRecordByKey_Call struct {
	*mock.Call
}

// RemoveRecordByKey is a helper method to define mock.On call
//  - ctx context.Context
//  - key string
func (_e *RecordTextDataService_Expecter) RemoveRecordByKey(ctx interface{}, key interface{}) *RecordTextDataService_RemoveRecordByKey_Call {
	return &RecordTextDataService_RemoveRecordByKey_Call{Call: _e.mock.On("RemoveRecordByKey", ctx, key)}
}

func (_c *RecordTextDataService_RemoveRecordByKey_Call) Run(run func(ctx context.Context, key string)) *RecordTextDataService_RemoveRecordByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RecordTextDataService_RemoveRecordByKey_Call) Return(_a0 error) *RecordTextDataService_RemoveRecordByKey_Call {
	_c.Call.Return(_a0)
	return _c
}

// SaveRecord provides a mock function with given fields: ctx, key, data
func (_m *RecordTextDataService) SaveRecord(ctx context.Context, key string, data clientmodels.RecordTextData) error {
	ret := _m.Called(ctx, key, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, clientmodels.RecordTextData) error); ok {
		r0 = rf(ctx, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecordTextDataService_SaveRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRecord'
type RecordTextDataService_SaveRecord_Call struct {
	*mock.Call
}

// SaveRecord is a helper method to define mock.On call
//  - ctx context.Context
//  - key string
//  - data clientmodels.RecordTextData
func (_e *RecordTextDataService_Expecter) SaveRecord(ctx interface{}, key interface{}, data interface{}) *RecordTextDataService_SaveRecord_Call {
	return &RecordTextDataService_SaveRecord_Call{Call: _e.mock.On("SaveRecord", ctx, key, data)}
}

func (_c *RecordTextDataService_SaveRecord_Call) Run(run func(ctx context.Context, key string, data clientmodels.RecordTextData)) *RecordTextDataService_SaveRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(clientmodels.RecordTextData))
	})
	return _c
}

func (_c *RecordTextDataService_SaveRecord_Call) Return(_a0 error) *RecordTextDataService_SaveRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

// NewRecordTextDataService creates a new instance of RecordTextDataService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewRecordTextDataService(t testing.TB) *RecordTextDataService {
	mock := &RecordTextDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
