// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	context "context"
	clientmodels "gophkeeper/client/clientmodels"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// RecordPersonalDataService is an autogenerated mock type for the RecordPersonalDataService type
type RecordPersonalDataService struct {
	mock.Mock
}

// LoadRecordByKey provides a mock function with given fields: ctx, key
func (_m *RecordPersonalDataService) LoadRecordByKey(ctx context.Context, key string) (clientmodels.RecordPersonalData, error) {
	ret := _m.Called(ctx, key)

	var r0 clientmodels.RecordPersonalData
	if rf, ok := ret.Get(0).(func(context.Context, string) clientmodels.RecordPersonalData); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(clientmodels.RecordPersonalData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveRecordByKey provides a mock function with given fields: ctx, key
func (_m *RecordPersonalDataService) RemoveRecordByKey(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveRecord provides a mock function with given fields: ctx, key, data
func (_m *RecordPersonalDataService) SaveRecord(ctx context.Context, key string, data clientmodels.RecordPersonalData) error {
	ret := _m.Called(ctx, key, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, clientmodels.RecordPersonalData) error); ok {
		r0 = rf(ctx, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecordPersonalDataService creates a new instance of RecordPersonalDataService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewRecordPersonalDataService(t testing.TB) *RecordPersonalDataService {
	mock := &RecordPersonalDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
